<a href="https://colab.research.google.com/github/ANKITA4545/Assignment-1-data-science-/blob/main/pdf_12_(numpy)2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arravali = np.array(np.random.randint(10,45,(8,2)))
print(f"The defined array is \n{arravali}")

print(f" \n The shape of the array is {arravali.shape}")

The defined array is 
[[16 22]
 [22 44]
 [21 23]
 [11 18]
 [16 30]
 [44 22]
 [29 15]
 [17 32]]
 
 The shape of the array is (8, 2)


In [4]:
nilgiri =np.transpose(arravali)
print(f" The transpose of the array is \n{nilgiri}")
print(f" \n The shape of the array is {nilgiri.shape}")

 The transpose of the array is 
[[16 22 21 11 16 44 29 17]
 [22 44 23 18 30 22 15 32]]
 
 The shape of the array is (2, 8)


In [5]:
random_3d_array = np.array(np.random.randint(10,45,(3,2,4)))
print(f"The defined array is \n{random_3d_array}")

print(f" \n The shape of the array is {random_3d_array.shape}")

The defined array is 
[[[25 31 14 29]
  [39 11 18 36]]

 [[30 27 24 10]
  [14 23 11 42]]

 [[26 39 17 27]
  [17 36 29 39]]]
 
 The shape of the array is (3, 2, 4)


In [6]:
transposed_3d_array =np.transpose(random_3d_array)

print(f" The transpose of the array is \n{transposed_3d_array}")
print(f" \n The shape of the array is {transposed_3d_array.shape}")

 The transpose of the array is 
[[[25 30 26]
  [39 14 17]]

 [[31 27 39]
  [11 23 36]]

 [[14 24 17]
  [18 11 29]]

 [[29 10 27]
  [36 42 39]]]
 
 The shape of the array is (4, 2, 3)


In [7]:
random_cohort = np.array(np.random. randint(10,45,(3,8))) # 2D
print(f"The defined array is \n{random_cohort}")

print(f" \n The shape of the array is {random_cohort.shape}")

The defined array is 
[[39 37 11 44 10 13 43 27]
 [28 19 25 11 16 38 20 25]
 [13 12 43 26 24 40 32 41]]
 
 The shape of the array is (3, 8)


In [8]:
new_shape = (2,6,2)

reshaped_random_cohort = np.reshape(random_cohort, new_shape)
print(f"The reshaped array is \n{reshaped_random_cohort}")

print(f" \n The shape of the array is {reshaped_random_cohort.shape}")

The reshaped array is 
[[[39 37]
  [11 44]
  [10 13]
  [43 27]
  [28 19]
  [25 11]]

 [[16 38]
  [20 25]
  [13 12]
  [43 26]
  [24 40]
  [32 41]]]
 
 The shape of the array is (2, 6, 2)


In [10]:
random_3D_cohort = np.array(np.random.randint(10,45,(3,6,2)))
print(f"The defined array is \n{random_3D_cohort}")

print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[11 32]
  [25 23]
  [14 13]
  [17 21]
  [24 35]
  [41 34]]

 [[37 20]
  [25 12]
  [10 21]
  [18 16]
  [10 40]
  [38 40]]

 [[17 10]
  [27 22]
  [41 15]
  [29 21]
  [25 37]
  [32 38]]]
 
 The shape of the array is (3, 6, 2)


In [11]:

new_shape = (2,-1,6)

reshaped_random_3D_cohort = np.reshape(random_3D_cohort, new_shape)
print(f"The reshaped array is \n{reshaped_random_3D_cohort}")

print(f" \n The shape of the array is {reshaped_random_3D_cohort.shape}")

The reshaped array is 
[[[11 32 25 23 14 13]
  [17 21 24 35 41 34]
  [37 20 25 12 10 21]]

 [[18 16 10 40 38 40]
  [17 10 27 22 41 15]
  [29 21 25 37 32 38]]]
 
 The shape of the array is (2, 3, 6)


In [12]:
random_3D_cohort = np.array(np.random.randint(16,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")

print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[23 37 20 38 40 16]
  [28 19 26 24 26 27]
  [39 16 37 41 18 35]
  [36 40 20 35 31 38]]

 [[18 28 43 20 18 34]
  [31 29 40 31 44 22]
  [20 35 30 42 22 24]
  [44 34 38 28 34 18]]]
 
 The shape of the array is (2, 4, 6)


In [13]:
new_shape = (2,3,6)

resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"The resized array is \n{resized_random_3D_cohort}")

print(f" \n The shape of the array is {resized_random_3D_cohort.shape}")

The resized array is 
[[[23 37 20 38 40 16]
  [28 19 26 24 26 27]
  [39 16 37 41 18 35]]

 [[36 40 20 35 31 38]
  [18 28 43 20 18 34]
  [31 29 40 31 44 22]]]
 
 The shape of the array is (2, 3, 6)


In [19]:
random_3D_cohort.resize(new_shape, refcheck=False)


print(random_3D_cohort)

[[[23 37 20 38 40 16]
  [28 19 26 24 26 27]
  [39 16 37 41 18 35]]

 [[36 40 20 35 31 38]
  [18 28 43 20 18 34]
  [31 29 40 31 44 22]]]


In [21]:
random_3D_cohort = np.array(np.random. randint(16,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")

print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[29 41 32 38 20 40]
  [36 35 32 24 36 31]
  [20 24 39 27 42 28]
  [38 24 36 43 31 17]]

 [[29 29 22 29 44 21]
  [34 41 31 37 21 25]
  [28 31 28 26 43 43]
  [18 43 24 39 30 16]]]
 
 The shape of the array is (2, 4, 6)


In [22]:
random_3D_cohort.flatten()

array([29, 41, 32, 38, 20, 40, 36, 35, 32, 24, 36, 31, 20, 24, 39, 27, 42,
       28, 38, 24, 36, 43, 31, 17, 29, 29, 22, 29, 44, 21, 34, 41, 31, 37,
       21, 25, 28, 31, 28, 26, 43, 43, 18, 43, 24, 39, 30, 16])

In [23]:
random_3D_cohort.flatten(order='F')

array([29, 29, 36, 34, 20, 28, 38, 18, 41, 29, 35, 41, 24, 31, 24, 43, 32,
       22, 32, 31, 39, 28, 36, 24, 38, 29, 24, 37, 27, 26, 43, 39, 20, 44,
       36, 21, 42, 43, 31, 30, 40, 21, 31, 25, 28, 43, 17, 16])

In [26]:

a = np.random. randint(10, 26, (2,3,4)) # Axis @ - 2 3; Axis 1-3 5 Axis 2-4
print(a)

print (a.shape)

[[[11 14 12 16]
  [25 25 21 14]
  [25 13 19 15]]

 [[24 20 23 17]
  [24 13 19 22]
  [11 24 13 23]]]
(2, 3, 4)


In [27]:
np.insert(a,1,100,axis=0)

array([[[ 11,  14,  12,  16],
        [ 25,  25,  21,  14],
        [ 25,  13,  19,  15]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 24,  20,  23,  17],
        [ 24,  13,  19,  22],
        [ 11,  24,  13,  23]]])

In [28]:
np.insert(a,0,50,axis=1)

array([[[50, 50, 50, 50],
        [11, 14, 12, 16],
        [25, 25, 21, 14],
        [25, 13, 19, 15]],

       [[50, 50, 50, 50],
        [24, 20, 23, 17],
        [24, 13, 19, 22],
        [11, 24, 13, 23]]])

In [30]:

a = np.random. randint(2,6,(2,3,3))

print(a)
print(a.shape)

[[[5 2 5]
  [4 4 2]
  [2 3 2]]

 [[3 4 4]
  [2 5 2]
  [4 4 2]]]
(2, 3, 3)


In [31]:
np.append(a, 50)

array([ 5,  2,  5,  4,  4,  2,  2,  3,  2,  3,  4,  4,  2,  5,  2,  4,  4,
        2, 50])

In [32]:
b = np.random.randint(2,6,(2,1,3))

print(b)

[[[4 4 3]]

 [[2 2 5]]]


In [33]:
print(a)
print (a.shape)

[[[5 2 5]
  [4 4 2]
  [2 3 2]]

 [[3 4 4]
  [2 5 2]
  [4 4 2]]]
(2, 3, 3)


In [34]:
np.append(a,b,axis = 1)

array([[[5, 2, 5],
        [4, 4, 2],
        [2, 3, 2],
        [4, 4, 3]],

       [[3, 4, 4],
        [2, 5, 2],
        [4, 4, 2],
        [2, 2, 5]]])

In [35]:
a = np.random.randint(2,20,(2,3,3))
print(a)

print (a.shape)

[[[17 17 18]
  [15 14 19]
  [ 5 12  7]]

 [[11  4 11]
  [17  5 10]
  [16  9 12]]]
(2, 3, 3)


In [36]:
np.unique(a)

array([ 4,  5,  7,  9, 10, 11, 12, 14, 15, 16, 17, 18, 19])

In [37]:
np.unique(a,return_counts=True) # Returns tuple

(array([ 4,  5,  7,  9, 10, 11, 12, 14, 15, 16, 17, 18, 19]),
 array([1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 3, 1, 1]))

In [38]:
np.unique(a, return_counts=True, return_index=True)

(array([ 4,  5,  7,  9, 10, 11, 12, 14, 15, 16, 17, 18, 19]),
 array([10,  6,  8, 16, 14,  9,  7,  4,  3, 15,  0,  2,  5]),
 array([1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 3, 1, 1]))

In [39]:
a = [1,2,3]

b = a

b[0] = 108

print(b)

print(a)

[108, 2, 3]
[108, 2, 3]


In [40]:
a = [1,2,3]

b = a.copy()

b[0] = 10

print (b)

print (a)

[10, 2, 3]
[1, 2, 3]


In [41]:
a = np.array([2,34,12])
b=a

b[0] = -999

print(b)

print(a)

[-999   34   12]
[-999   34   12]


In [43]:
np.array([2,34,12])
a.copy()

b[0] = -999

print(b)


[-999   34   12]


In [44]:
np.arange(3) + 5

array([5, 6, 7])

In [45]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [46]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [47]:

np. arange(3).reshape((3,1)) + np.arange(4)


array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [49]:
np.arange(2)

array([0, 1])

In [50]:
a=np.random.randint(2,6,(2,4))
print(a)
b=np.random.randint(1,10, (2,2))
print (b)

[[4 2 4 3]
 [2 3 4 2]]
[[7 2]
 [7 6]]


In [51]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,4) (2,2) 

In [53]:
a=np.random.randint(2,6, (2,4))
print(a)
b=np.random.randint(0,5,(2,4))
print(b)

[[4 3 3 2]
 [4 4 4 5]]
[[1 1 2 2]
 [0 3 2 2]]


In [54]:
np.multiply(a,b)

array([[ 4,  3,  6,  4],
       [ 0, 12,  8, 10]])

In [55]:
np.divide(a,b)

<ipython-input-55-c364992e28ce>:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)


array([[4.        , 3.        , 1.5       , 1.        ],
       [       inf, 1.33333333, 2.        , 2.5       ]])

In [56]:

a=np.random.randint(5,9,(2,4))
print(a)

[[6 6 8 7]
 [5 8 5 6]]


In [57]:
print(np.sum(a))
print(np.sum(a,axis=0) )
print (np.sum(a, axis=1))

51
[11 14 13 13]
[27 24]


In [61]:
print (np.min(a)) # Minimum of the entire array
print (np.min(a,axis=0)) # Minimum across rows (axis 0)
print (np.min(a, axis=1)) # Minimum across columns (axis 1)

5
[5 6 5 6]
[6 5]


In [64]:
print(np.sort(a, axis=1))  # Sort along axis 1 (columns) or
print(np.sort(a, axis=0))  # Sort along axis 0 (rows)

[[6 6 7 8]
 [5 5 6 8]]
[[5 6 5 6]
 [6 8 8 7]]
